// <auto-generated />
using System;
using CatInvaders.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatInvaders.API.Migrations
{
    [DbContext(typeof(CatInvadersDbContext))]
    [Migration("20260403172113_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("CatInvaders.API.Domain.HighScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LevelReached")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Score", "CreatedAtUtc")
                        .HasDatabaseName("IX_HighScores_Score_CreatedAtUtc");

                    b.ToTable("HighScores", t =>
                        {
                            t.HasCheckConstraint("CK_HighScores_Score", "\"Score\" >= 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
